pipeline {
  agent {
    docker { image 'python:3.9-alpine' } // Use Python image
  }
  stages {
    stage('Run Python Script') {
      steps {
        sh 'python3 my_first_pipeline/python/main.py' // Run the script
      }
    }
  }
}
