pipeline {
  agent {
    docker { image 'python:3.9-alpine' } // Use Python image
  }
  stages {
    stage('Run Python Script') {
      steps {
        sh 'pwd'
        sh 'ls -R'  // Run the script
      }
    }
  }
}
